name: flood_mobile
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # flutter pub run build_runner watch --delete-conflicting-outputs
  dropdown_button2: ^2.1.3
  clipboard: ^0.1.3
  cupertino_icons: ^1.0.3
  chewie: ^1.2.2
  dio: ^5.1.2
  duration: ^3.0.6
  expansion_tile_card: ^3.0.0
  flutter_keyboard_visibility: ^5.0.3
  flutter_svg: ^2.0.6
  flutter_slidable: ^3.0.0
  flutter_spinkit: ^5.0.0
  fluttertoast: ^8.0.8
  file_picker: ^5.2.10
  focused_menu: ^1.0.5
  font_awesome_flutter: ^10.4.0
  google_fonts: ^4.0.4
  hidden_drawer_menu: ^3.0.0
  http: ^0.13.3
  json_annotation: ^4.1.0
  json_patch: ^3.0.0
  loading_overlay: ^0.3.0
  percent_indicator: ^4.2.3
  provider: ^6.0.5
  shared_preferences: ^2.0.6
  video_player: ^2.1.12
  badges: ^3.1.1
  flutter_downloader: ^1.6.1
  path_provider: ^2.0.2
  permission_handler: ^10.2.0
  flutter_client_sse: ^2.0.0-beta.1
  url_launcher: ^6.0.12
  optimize_battery: ^0.0.4
  smooth_page_indicator: ^1.0.0+2
  awesome_notifications: ^0.7.0-beta.1
  uri_to_file: ^0.2.0
  bottom_sheet: ^3.1.1
  contained_tab_bar_view: ^0.8.0
  uni_links: ^0.5.1
  flutter_speed_dial: ^7.0.0
  syncfusion_flutter_charts: ^21.2.8
    #    git:
    #      url: https://github.com/pratikbaid3/flutter_client_sse
    #      path:
    #path: packages/flutter_client_sse

dependency_overrides:
  meta: ^1.7.0
  analyzer: ^3.0.0

dev_dependencies:
  build_runner: ^2.1.1
  json_serializable: ^6.7.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
