const Languages = {
  'auto': 'Automatic',
  'en': 'English',
  'hi': 'हिन्दी',
  'cs': 'Čeština',
  'de': 'Deutsch',
  'es': 'Español',
  'fr': 'Français',
  'it': 'italiano',
  'hu': 'Magyar',
  'nl': 'Nederlands',
  'no': 'norsk',
  'pl': 'Polskie',
  'pt': 'português',
  'ru': 'русский язык',
  'ro': 'Romanian',
  'fi': 'suomi',
  'sv': 'svenska',
  'uk': 'українська мова',
  'ko': '한국어',
  'ja': '日本語',
  'zh': '中文(繁體)',
  'ar': 'اَلْعَرَبِيَّةُ',
};
