blank_issues_enabled: true
contact_links:
  - name: Have any issues or feature requests to discuss for Flood
    url: https://slackinvite.ccextractor.org/
    about: Join us on Slack and meet members and contributors
