name: Flutter CI

on:
  push:
    branches: [ master , develop ]
  pull_request:
    branches: [ master , develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.13.1'
      - run: flutter pub get
      - run: flutter gen-l10n --arb-dir=lib/l10n/arb
      - run: flutter analyze
      - run: dart format --output=none --set-exit-if-changed .
      - run: flutter test
      - run: flutter build apk

      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
